total_runs: 12
label_counts:
  PERSON_FIRST_NAME: 74
  PERSON_LAST_NAME: 82
  EMPLOYEE_ID: 17
  PERSON_MIDDLE_NAME: 11
  INSURANCE_POLICY: 6
  HEALTH_INSURANCE_ID: 2
  DATE_OF_BIRTH: 22
  SSN: 27
  DRIVERS_LICENSE_NUMBER: 8
  LICENSE_PLATE_NUMBER: 4
  VIN: 5
  MEDICAL_RECORD_NUMBER: 6
  NATIONAL_ID: 2
  PRESCRIPTION_NUMBER: 5
  PROFESSIONAL_LICENSE_NUMBER: 5
  MEDICARE_MEDICAID_ID: 2
  DISABILITY_STATUS: 1
  COURT_CASE_NUMBER: 2
  PHONE_NUMBER: 24
  PHI: 4
  MEDICAL_DEVICE_SERIAL: 2
  HEALTH_PLAN_BENEFICIARY_NUMBER: 2
  EMAIL_ADDRESS: 18
  NATIONALITY: 4
  BANK_ACCOUNT_LAST4: 1
  MOTHERS_MAIDEN_NAME: 1
  IBAN: 1
  ROUTING_NUMBER: 4
  STREET_ADDRESS: 15
  ACCOUNT_LAST4: 1
  MR_NUMBER: 4
  CARD_SECURITY_CODE: 1
  EMPLOYER_NAME: 3
  CARDMEMBER_ID: 2
  MORTGAGE_LOAN_INFO: 6
  PROPERTY_TAX_PARCEL: 1
  INCOME: 7
  FICO_SCORE: 1
  INVESTMENT_ACCOUNT_NUMBER: 2
  CUSIP_NUMBER: 1
  EMERGENCY_CONTACT_INFORMATION: 6
  PASSPORT_NUMBER: 1
  PUBLIC_ASSISTANCE_RECEIPT: 1
  GENERIC_LAST4: 1
  NON_DRIVERS_ID: 1
  PIN: 3
  AGE: 6
  TAX_ID: 5
  CHILDREN_INFORMATION: 2
source_counts:
  propagated: 44
  derived: 94
  gliner: 147
  regex: 122
  context: 5
label_source_counts:
  PERSON_FIRST_NAME|propagated: 17
  PERSON_LAST_NAME|propagated: 27
  PERSON_FIRST_NAME|derived: 39
  PERSON_LAST_NAME|derived: 44
  EMPLOYEE_ID|gliner: 16
  PERSON_MIDDLE_NAME|derived: 11
  INSURANCE_POLICY|gliner: 6
  HEALTH_INSURANCE_ID|gliner: 2
  DATE_OF_BIRTH|gliner: 22
  SSN|regex: 27
  DRIVERS_LICENSE_NUMBER|gliner: 8
  LICENSE_PLATE_NUMBER|regex: 2
  VIN|regex: 5
  LICENSE_PLATE_NUMBER|gliner: 2
  MEDICAL_RECORD_NUMBER|gliner: 6
  NATIONAL_ID|gliner: 2
  PRESCRIPTION_NUMBER|gliner: 5
  PROFESSIONAL_LICENSE_NUMBER|regex: 3
  MEDICARE_MEDICAID_ID|regex: 2
  DISABILITY_STATUS|regex: 1
  COURT_CASE_NUMBER|regex: 2
  PHONE_NUMBER|regex: 24
  PHI|gliner: 2
  MEDICAL_DEVICE_SERIAL|gliner: 2
  HEALTH_PLAN_BENEFICIARY_NUMBER|gliner: 2
  EMAIL_ADDRESS|regex: 18
  PROFESSIONAL_LICENSE_NUMBER|gliner: 2
  PERSON_LAST_NAME|gliner: 11
  PERSON_FIRST_NAME|gliner: 18
  NATIONALITY|regex: 4
  BANK_ACCOUNT_LAST4|context: 1
  MOTHERS_MAIDEN_NAME|gliner: 1
  IBAN|gliner: 1
  ROUTING_NUMBER|regex: 4
  STREET_ADDRESS|regex: 12
  ACCOUNT_LAST4|context: 1
  MR_NUMBER|regex: 3
  CARD_SECURITY_CODE|gliner: 1
  EMPLOYER_NAME|gliner: 3
  MR_NUMBER|gliner: 1
  CARDMEMBER_ID|gliner: 2
  STREET_ADDRESS|gliner: 3
  MORTGAGE_LOAN_INFO|gliner: 6
  PROPERTY_TAX_PARCEL|gliner: 1
  INCOME|regex: 6
  FICO_SCORE|gliner: 1
  INVESTMENT_ACCOUNT_NUMBER|gliner: 2
  CUSIP_NUMBER|regex: 1
  EMERGENCY_CONTACT_INFORMATION|gliner: 6
  PASSPORT_NUMBER|gliner: 1
  PHI|regex: 2
  PUBLIC_ASSISTANCE_RECEIPT|regex: 1
  GENERIC_LAST4|context: 1
  NON_DRIVERS_ID|gliner: 1
  PIN|regex: 3
  EMPLOYEE_ID|context: 1
  AGE|gliner: 4
  AGE|regex: 2
  TAX_ID|gliner: 4
  INCOME|gliner: 1
  TAX_ID|context: 1
  CHILDREN_INFORMATION|gliner: 2
last_updated: '2026-03-25T02:26:44.979638'
